image: maven:3.6.3

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
          after-script:
            - pipe: atlassian/checkstyle-report:0.3.0
          artifacts:
            - target/*.war
      - step:
          name: Security Scan
          script:
            - pipe: atlassian/git-secrets-scan:0.5.1
            
    - step:
        name: Deploy
        runs-on:
          - self.hosted
          - linux.shell
        script:
          - mkdir artifacts
          - mkdir artifacts/target
          - cp -R scripts artifacts
          - cp target/*war artifacts/target
          - cp appspec.yml artifacts
          - zip -r artifacts.zip artifacts
          
          - aws s3api put-object
            --bucket "$BUCKET"
            --key "artifacts/$BITBUCKET_COMMIT.zip"
            --body artifacts.zip

          - aws deploy create-deployment
            --region us-east-2
            --application-name $APPLICATION_NAME
            --deployment-config-name CodeDeployDefault.OneAtATime
            --deployment-group-name $DEPLOYMENT_GROUP
            --s3-location bucket=$BUCKET,bundleType=zip,key=artifacts/$BITBUCKET_COMMIT.zip